workflows:
  android-build:
    name: Build and Deploy
    environment:
      vars:
        BASE_URL: "http://sistemacar.ct.ws"
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/**/*.apk
